### ISSUE TITLE
大佬，启动iopaint_server.py时候报错有解决方法吗T-T

### ISSUE THREAD

**Issue by smalltownkids** [Samge0/yolo8-plus-iopaint#1]
PS D:\desktop\shixi\yolo8-plus-iopaint-main\yolo8-plus-iopaint-main> & d:/anaconda/envs/yolo/python.exe d:/desktop/shixi/yolo8-plus-iopaint-main/yolo8-plus-iopaint-main/iopaint_server.py
Traceback (most recent call last):
  File "d:/desktop/shixi/yolo8-plus-iopaint-main/yolo8-plus-iopaint-main/iopaint_server.py", line 39, in <module>
    start_iopaint_server()
  File "d:/desktop/shixi/yolo8-plus-iopaint-main/yolo8-plus-iopaint-main/iopaint_server.py", line 32, in start_iopaint_server
    process = subprocess.Popen(command)
  File "D:\anaconda\envs\yolo\lib\subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "D:\anaconda\envs\yolo\lib\subprocess.py", line 1327, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

**Comment by Samge0** [comment]
感谢反馈，实在不好意思，现在才看到这消息。

 该问题现已处理：[fix：在非项目根路径执行脚本提示”系统找不到指定的文件“的问题](https://github.com/Samge0/yolo8-plus-iopaint/pull/2) #2

**Comment by Samge0** [comment]
可以拉取最新代码重试一下
